#!/usr/bin/env bash

# Many thanks to Chris Swain for helping to make this script work properly on OSX

# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$0
cd `dirname $SCRIPT`
SCRIPT=`basename $SCRIPT`
# Iterate down a (possible) chain of symlinks
while [ -L "$SCRIPT" ]
do
    SCRIPT=`readlink $SCRIPT`
    cd `dirname $SCRIPT`
    SCRIPT=`basename $SCRIPT`
done
PHYS_DIR=`pwd -P`
SCRIPT=$PHYS_DIR/$SCRIPT

# Linux version
# SCRIPT=$(readlink -f "$0")

# Absolute path this script is in, thus /home/user/bin
SCRIPTDIR=$(dirname "$SCRIPT")

java -jar "$SCRIPTDIR/fame2.jar" "$@"